config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path, include
from django.views.static import serve
from django.contrib.auth import views as auth_views
from config import app_seo as seo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('mck_auth.urls', namespace='mck_auth')),
    path('mck-master/', include('mck_master.urls', namespace='mck_master')),

    path('change-password/',auth_views.PasswordChangeView.as_view(
                                        extra_context={'page_kwargs':seo.get_page_tags("password_change")}),
                                        name='password_change'),
    path('change-password/complete/',auth_views.PasswordChangeDoneView.as_view(
                                        extra_context={'page_kwargs':seo.get_page_tags("password_change_done")}),
                                        name='password_change_done'),

    path('', include('mck_website.urls', namespace='vlr_website')),
    path('mck-admin-console/', include('mck_admin_console.urls', namespace='mck_admin_console')),
    path('squarebox/', include('squarebox.urls', namespace='squarebox')),

    re_path(r'^app-static/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_STATIC_ROOT}),
    re_path(r'^site-media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

mck_website/urls.py
from django.urls import path
from mck_website import views

app_name = "mck_website"

urlpatterns = [

    # path(".well-known/pki-validation/0021C33903EBC802E268A3D626130F22.txt", views.pki_validation_view, name="pki_validation"),
    path('', views.HomePage.as_view(), name='home_page'),
    path('about/', views.AboutPage.as_view(), name='about_page'),
    path('pricing/', views.PropertyLegalServicesPage.as_view(), name='pricing'),
    path('our-services/', views.OurServicesPage.as_view(), name='our_services_page'),
    path('privacy-policy/', views.PrivacyPolicyPage.as_view(), name='privacy_policy_page'),
    path('terms/', views.TermsPage.as_view(), name='terms_page'),
    path('solar/',views.SolarPage.as_view(), name='solar_page'),
    path('fencing/',views.FencingPage.as_view(), name='fencing_page'),
    path('land-levelling/',views.LandLevellingPage.as_view(), name='land_levelling_page'),
    path("Profile-detail/", views.ProfilePage.as_view(), name="mck_property_page"),
    path('property-details/<int:pk>/', views.PropertyDetailPage.as_view(), name='property_detail'),
    path(
        "property_create/",
        views.PropertyCreatePage.as_view(),
        name="mck_property_create_page",
    ),
    path(
        "maintenances/",
        views.MaintenancesCreatePage.as_view(),
        name="property_maintenance_page",
    ),
    path(
        "enquiry/",
        views.EnquiryCreatePage.as_view(),
        name="property_enquiry_page",
    ),
    path('ajax/property/save/', views.PropertySaveView.as_view(),name='mck_ajax_property_save'),
    path('ajax/maintenances/save/', views.MaintenanceSaveView.as_view(),name='mck_ajax_maintenance_save'),
    path('ajax/lead/save/', views.EnquirySaveView.as_view(),name='mck_ajax_enquiry_save'),


    # path(
    #     "profile/",
    #     views.EnquiryCreatePage.as_view(),
    #     name="profile_page",
    # ),

   path('ajax/profile/save/', views.ProfileSaveView.as_view(),name='mck_ajax_profile_save'),
#    path("profile/<int:pk>/", views.ProfileDetailPage.as_view(), name="profile_detail"),
# Correct order
            path("profile/<int:pk>/", views.ProfileDetailPage.as_view(), name="profile_detail"),
            path("profile/", views.EnquiryCreatePage.as_view(), name="profile_page"),
            path("my-profile/", views.MyProfilePage.as_view(), name="my_profile"),
            # mck_website/urls.py
            path(
                "ajax/my-profile/save/",
                views.ajax_profile_save,
                name="mck_ajax_my_profile_save"
            ),



]

mck_website/views.py
"""
Views - VLR Website App
"""

from django.http import HttpResponse
import os
from django.conf import settings
from django.shortcuts import render
from django.views.generic import TemplateView
from django.shortcuts import render, get_object_or_404
from config import app_logger
from config import app_seo as seo
from squarebox.models import *
from mck_website.api import *
from mck_website.models import *
from django.urls import reverse 
from django.db.models import Prefetch
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from mck_auth import build_table as bt
from mck_auth import role_validations as rv
from squarebox import api
from squarebox import forms
from squarebox import models
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic import TemplateView
from django.shortcuts import render
from django.core.paginator import Paginator
from datetime import date
from dateutil.relativedelta import relativedelta
from mck_master.models import Profile


LOG_NAME = "app"
logger = app_logger.createLogger(LOG_NAME)


def pki_validation_view(request):
    file_path = os.path.join(settings.BASE_DIR, "mck_website", "templates", "verify.txt")
    try:
        with open(file_path, "r") as file:
            content = file.read()
        return HttpResponse(content, content_type="text/plain")
    except FileNotFoundError:
        return HttpResponse("File not found", status=404)



class HomePage(TemplateView):
    """
    Home Page
    """
    template_name = "home.html"

    @app_logger.functionlogs(log=LOG_NAME)
    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_kwargs'] = seo.get_page_tags("home_page")

        context["property"] = Property.objects.exclude(datamode='D').order_by('-updated_on')
        context["profile"] = Profile.objects.exclude(datamode='D').order_by('-updated_on')
        context["property_type"] = PropertyType.objects.exclude(datamode='D').order_by('-updated_on')
        context["property_image"] = PropertyImage.objects.exclude(datamode='D').order_by('-updated_on')
        context["lead"] = Lead.objects.exclude(datamode='D').order_by('-updated_on')
        context["cities"] = Property.objects.exclude(datamode='D') \
                                            .values_list('city', flat=True) \
                                            .distinct() \
                                            .order_by('city')
        context["property"] = (
            Property.objects.exclude(datamode='D')
            .prefetch_related(
                Prefetch('images', queryset=PropertyImage.objects.exclude(datamode='D'))
            )
            .order_by('-updated_on')
)

        logger.info(request.GET)
        return render(request, self.template_name, context)


class PropertyPage(TemplateView):
    template_name = "property_page.html"

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Get all properties excluding deleted ones
        qs = Property.objects.exclude(datamode='D')
        
        # Apply filters
        city = request.GET.get('city')
        listing_type = request.GET.get("listing_type")
        property_type = request.GET.get('property_type')
        budget = request.GET.get('budget')
        sort = request.GET.get('sort', 'newest')

        if city:
            qs = qs.filter(city__icontains=city)

        if property_type:
            qs = qs.filter(property_type__name__iexact=property_type)

        if listing_type:
            qs = qs.filter(listing_type__iexact=listing_type)

        if budget:
            if budget == "Below 100k":
                qs = qs.filter(price__lt=100000)
            elif budget == "100k - 300k":
                qs = qs.filter(price__range=(100000, 300000))
            elif budget == "Above 300k":
                qs = qs.filter(price__gt=300000)

        # Apply sorting
        if sort == 'price_low':
            qs = qs.order_by('price')
        elif sort == 'price_high':
            qs = qs.order_by('-price')
        else:  # newest
            qs = qs.order_by('-updated_on')

       

        # Pagination
        paginator = Paginator(qs, 9)  # Show 9 properties per page
        page_number = request.GET.get('page')
        properties = paginator.get_page(page_number)
        
        # Prefetch related images
        properties.object_list = properties.object_list.prefetch_related(
            Prefetch(
                'images',  
                queryset=PropertyImage.objects.exclude(datamode='D').order_by('-updated_on'),
                to_attr='property_images_list'  
            )
        )

        context["properties"] = properties
        context["property_types"] = PropertyType.objects.exclude(datamode='D').order_by('-updated_on')
        context["cities"] = (
            Property.objects.exclude(datamode='D')
            .values_list('city', flat=True)
            .distinct()
            .order_by('city')
        )

        return render(request, self.template_name, context)


class PropertyDetailPage(TemplateView):
    template_name = "resources.html"

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        property_id = kwargs.get('pk')  # from URL
        property_obj = get_object_or_404(
            Property.objects.prefetch_related(
                Prefetch(
                    'images',
                    queryset=PropertyImage.objects.exclude(datamode='D').order_by('-updated_on')
                )
            ),
            pk=property_id
        )

        context["property"] = property_obj
        return render(request, self.template_name, context)

class PropertyCreatePage(TemplateView):
    template_name = "pages/property_create.html"

    @app_logger.functionlogs(log=LOG_NAME)
    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_kwargs"] = seo.get_page_tags("property_create")
        property = Property.objects.exclude(datamode='D').order_by('-updated_on')
        context["property"] = property
        logger.info(request.GET)
        return render(request, self.template_name, context)
    
    
class MaintenancesCreatePage(TemplateView):
    template_name = "pages/faq.html"

    @app_logger.functionlogs(log=LOG_NAME)
    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_kwargs"] = seo.get_page_tags("maintenance")
        maintenance = MaintenanceRequest.objects.exclude(datamode='D').order_by('-updated_on')
        context["maintenance"] = maintenance
        logger.info(request.GET)
        return render(request, self.template_name, context)
    

class PropertySaveView(TemplateView):
    def post(self, request, *args, **kwargs):
        try:
            logger.info("Received property save request")
            logger.info("POST data: %s", request.POST)
            logger.info("FILES data: %s", request.FILES)
            
            result, message = api.ajax_property_save(request)
            if result:
                logger.info("Property saved successfully")
                return JsonResponse({"status": "success", "message": message})
            else:
                logger.error("Failed to save property: %s", message)
                return JsonResponse({"status": "fail", "message": message}, status=400)
                
        except Exception as e:
            logger.exception("Unexpected error in PropertySaveView")
            return JsonResponse({"status": "error", "message": str(e)}, status=500)
        

class MaintenanceSaveView(TemplateView):
    def post(self, request, *args, **kwargs):
        try:
            logger.info("Received Maintenance save request")
            logger.info("POST data: %s", request.POST)
            logger.info("FILES data: %s", request.FILES)
            
            result, message = api.ajax_maintenance_save(request)
            if result:
                logger.info("maintenance saved successfully")
                return JsonResponse({"status": "success", "message": message})
            else:
                logger.error("Failed to save maintenance: %s", message)
                return JsonResponse({"status": "fail", "message": message}, status=400)
                
        except Exception as e:
            logger.exception("Unexpected error in maintenanceSaveView")
            return JsonResponse({"status": "error", "message": str(e)}, status=500)
        
        
class EnquiryCreatePage(TemplateView):
    template_name = "includes/enquiry.html"

    @app_logger.functionlogs(log=LOG_NAME)
    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_kwargs"] = seo.get_page_tags("lead")
        lead = Lead.objects.exclude(datamode='D').order_by('-updated_on')
        context["lead"] = lead
        property_type = request.GET.get('property_type', '')
        context["selected_property_type"] = property_type  
        logger.info(request.GET)
        return render(request, self.template_name, context)

class EnquirySaveView(TemplateView):
    def post(self, request, *args, **kwargs):
        try:
            logger.info("Received lead save request")
            logger.info("POST data: %s", request.POST)
            logger.info("FILES data: %s", request.FILES)
            
            result, message = api.ajax_enquiry_save(request)
            if result:
                logger.info("lead saved successfully")
                return JsonResponse({"status": "success", "message": message})
            else:
                logger.error("Failed to save lead: %s", message)
                return JsonResponse({"status": "fail", "message": message}, status=400)
                
        except Exception as e:

mck_website/templates/pages/maintenance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Maintenance Request Form</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        body {
            background-color: #f9fafb;
        }
        .form-card {
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.05);
            padding: 25px;
            margin-bottom: 30px;
        }
        .form-header h2 {
            font-size: 24px;
            font-weight: 700;
            color: #2c3e50;
        }
        .form-subtitle {
            color: #6c757d;
            font-size: 15px;
        }
        .section-title {
            font-size: 18px;
            font-weight: 600;
            margin-bottom: 15px;
            color: #2c3e50;
        }
        .form-label {
            font-weight: 500;
            margin-bottom: 6px;
        }
        .upload-area {
            border: 2px dashed #ced4da;
            border-radius: 8px;
            padding: 25px;
            text-align: center;
            background-color: #f8f9fa;
            cursor: pointer;
        }
        .upload-area.dragover {
            border-color: #0d6efd;
            background-color: #eef6ff;
        }
        .file-preview-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
            gap: 12px;
            margin-top: 15px;
        }
        .preview-item {
            border: 1px solid #dee2e6;
            border-radius: 6px;
            padding: 8px;
            background: #fff;
        }
        .file-name {
            font-size: 14px;
            font-weight: 500;
            color: #2c3e50;
        }
        .file-size {
            font-size: 12px;
            color: #6c757d;
        }
        .btn-primary {
            border-radius: 8px;
            padding: 10px 25px;
            font-weight: 600;
        }
        .alert-danger {
            border-radius: 6px;
            padding: 12px;
            margin-bottom: 20px;
        }
/* Hero */
    .hero {
      margin-top:18px;
      background: linear-gradient(135deg, rgba(255,210,0,0.12) 0%, rgba(0,80,158,0.03) 100%);
      padding: 48px 0;
      border-radius: var(--radius);
      box-shadow: 0 12px 40px rgba(2,6,23,0.04);
      overflow:hidden;
    }
    .hero-grid{
      display:grid;
      grid-template-columns: 1fr 480px;
      gap:32px;
      align-items: center;
      max-width: var(--max-width);
      margin:0 auto;
      padding:36px var(--container-pad);
    }
    .hero-left h2{
      margin:0 0 12px 0;
      font-size:2.1rem;
      line-height:1.03;
      color:var(--dark);
      font-weight:800;
      letter-spacing:-0.02em;
    }
    .hero-left p{
      margin:0 0 18px 0;
      color:#394455;
      max-width:60ch;
      font-size:1rem;
    }
    .hero-actions{ display:flex; gap:12px; align-items:center; flex-wrap:wrap; margin-top:6px; }
    .btn-primary{
      background:var(--accent);
      color:#fff;
      border:none;
      padding:12px 20px;
      border-radius:10px;
      font-weight:700;
      box-shadow: 0 8px 20px rgba(0,80,158,0.12);
      transition: transform .18s ease, background .18s ease;
    }
    .btn-primary:hover{ transform:translateY(-3px); background:#003b7a;}
    .btn-ghost{
      background:transparent;
      border:2px solid rgba(17,17,17,0.06);
      color:var(--dark);
      padding:10px 16px;
      border-radius:10px;
      font-weight:700;
    }
    /* hero image card */
    .hero-card{
      background: linear-gradient(180deg, #fff, #fbfbfb);
      border-radius: 12px;
      overflow:hidden;
      box-shadow: 0 8px 30px rgba(17,17,17,0.06);
      display:flex;
      align-items:center;
      justify-content:center;
      min-height:320px;
    }
    .hero-card img{
      width:100%;
      height:100%;
      object-fit:cover;
      display:block;
    }

    /* Inline hero form - compact and modern */
    .hero-form{
      margin-top:20px;
      background: rgba(255,255,255,0.95);
      border-radius: 12px;
      padding:14px;
      display:flex;
      gap:10px;
      align-items:center;
      border:1px solid rgba(17,17,17,0.04);
      box-shadow: 0 10px 30px rgba(2,6,23,0.03);
      transition: box-shadow .18s ease, transform .18s ease;
    }
    .hero-form:hover{ box-shadow: 0 18px 48px rgba(2,6,23,0.05); transform: translateY(-2px); }
    .hero-form .form-input{
      flex:1;
      min-width:140px;
      padding:12px 14px;
      border-radius:8px;
      border:1px solid #e6e9ef;
      font-size:0.95rem;
    }
    .hero-form button{
      background:var(--primary);
      color:var(--dark);
      font-weight:700;
      padding:10px 14px;
      border-radius:8px;
      border:none;
      cursor:pointer;
      transition: transform .12s ease;
    }
    .hero-form button:hover{ transform: translateY(-2px); }

        
    </style>
</head>
<body>
    {% include "includes/header.html" %}

    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="form-card ">
                    <div class="form-header text-center mb-4">
                        <h2><i class="fas fa-tools me-2 text-primary"></i>Maintenance Request</h2>
                        <p class="form-subtitle">Report any maintenance issues with your property</p>
                    </div>

                    <form id="maintenance_form" method="POST" action="{% url 'vlr_website:mck_ajax_maintenance_save' %}" enctype="multipart/form-data" class="needs-validation" novalidate>
                        <!-- Error Message -->
                        <div class="alert alert-danger" id="form_error" style="display:none;"></div>

                        <!-- Request Details -->
                        <div class="mb-4">
                            <h5 class="section-title"><i class="fas fa-info-circle me-2 text-primary"></i>Request Details</h5>
                            <div class="mb-3">
                                <label class="form-label">Description <span class="text-danger">*</span></label>
                                <textarea name="description" class="form-control" rows="4" required placeholder="Describe the issue in detail"></textarea>
                                <div class="invalid-feedback">Please provide a description</div>
                            </div>

                            <div class="row g-3">
                                <div class="col-md-6">
                                    <label class="form-label">Urgency <span class="text-danger">*</span></label>
                                    <select name="urgency" class="form-select" required>
                                        <option value="">Select urgency</option>
                                        <option value="low">Low</option>
                                        <option value="medium" selected>Medium</option>
                                        <option value="high">High</option>
                                        <option value="urgent">Urgent</option>
                                    </select>
                                    <div class="invalid-feedback">Please select urgency</div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label">Preferred Date</label>
                                    <input type="date" name="preferred_date" class="form-control">
                                </div>
                            </div>
                        </div>

                        <!-- Attachments -->
                        <div class="mb-4">
                            <h5 class="section-title"><i class="fas fa-paperclip me-2 text-primary"></i>Attachments</h5>
                            <div class="file-upload-wrapper">
                                <input type="file" name="attachment" id="maintenance_attachments" class="d-none" multiple>
                                <div class="upload-area" id="upload_area">
                                    <i class="fas fa-cloud-upload-alt fa-2x text-primary mb-2"></i>
                                    <p class="mb-1">Drag & drop files or click to browse</p>
                                    <small class="text-muted">Max 5 files, 10MB each</small>
                                </div>
                                <div id="file-preview" class="file-preview-grid"></div>
                            </div>
                        </div>

                        <!-- Submit -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary" id="submit_btn">
                                <i class="fas fa-save me-2"></i> Submit Request
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% include "includes/footer_main.html" %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <script>
    $(document).ready(function() {
        const fileInput = $('#maintenance_attachments');
        const uploadArea = $('#upload_area');
        const filePreview = $('#file-preview');

        fileInput.on('change', function() {
            filePreview.empty();
            const files = this.files;
            if (files.length > 5) {
                showError("You can upload a maximum of 5 files");
                fileInput.val('');
                return;
            }
            for (let i = 0; i < files.length; i++) {
                const file = files[i];
                if (file.size > 10 * 1024 * 1024) {
                    showError(file.name + " is too large (max 10MB)");
                    fileInput.val('');
                    filePreview.empty();
                    return;
                }
                const previewItem = $('<div class="preview-item"></div>');
                previewItem.append('<div class="file-name">'+file.name+'</div>');
                previewItem.append('<div class="file-size">'+formatFileSize(file.size)+'</div>');
                filePreview.append(previewItem);
            }
        });

        uploadArea.on('click', function() { fileInput.click(); });
        uploadArea.on('dragover', function(e) { e.preventDefault(); $(this).addClass('dragover'); });
        uploadArea.on('dragleave', function(e) { e.preventDefault(); $(this).removeClass('dragover'); });
        uploadArea.on('drop', function(e) {
            e.preventDefault();
            $(this).removeClass('dragover');
            fileInput[0].files = e.originalEvent.dataTransfer.files;
            fileInput.trigger('change');
        });

        $('#maintenance_form').on('submit', function(e) {
            e.preventDefault();
            const form = $(this);
            const submitBtn = $('#submit_btn');
            submitBtn.prop('disabled', true);
            if (!form[0].checkValidity()) {
                form.addClass('was-validated');
                submitBtn.prop('disabled', false);
                return;
            }
            const formData = new FormData(form[0]);
            $.ajax({
                url: form.attr('action'),
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                headers: { 'X-CSRFToken': '{{ csrf_token }}' },
                success: function(res) {
                    if (res.status === "success") {
                        alert("Request submitted successfully!");
                        window.location.reload();
                    } else {
                        showError(res.message || "Failed to submit request");
                    }
                },
                error: function() { showError("An error occurred while submitting request"); },
                complete: function() { submitBtn.prop('disabled', false); }
            });
        });

        function formatFileSize(bytes) {
            if (bytes === 0) return '0 Bytes';
            const k = 1024, sizes = ['Bytes','KB','MB','GB'];
            const i = Math.floor(Math.log(bytes) / Math.log(k));
            return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
        }
        function showError(msg) {
            $('#form_error').text(msg).show();
            $('html, body').animate({ scrollTop: $('#form_error').offset().top - 100 }, 500);
        }
    });
    </script>
</body>
</html>