config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path, include
from django.views.static import serve
from django.contrib.auth import views as auth_views
from config import app_seo as seo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('mck_auth.urls', namespace='mck_auth')),
    path('mck-master/', include('mck_master.urls', namespace='mck_master')),

    path('change-password/',auth_views.PasswordChangeView.as_view(
                                        extra_context={'page_kwargs':seo.get_page_tags("password_change")}),
                                        name='password_change'),
    path('change-password/complete/',auth_views.PasswordChangeDoneView.as_view(
                                        extra_context={'page_kwargs':seo.get_page_tags("password_change_done")}),
                                        name='password_change_done'),

    path('', include('mck_website.urls', namespace='vlr_website')),
    path('mck-admin-console/', include('mck_admin_console.urls', namespace='mck_admin_console')),
    path('squarebox/', include('squarebox.urls', namespace='squarebox')),

    re_path(r'^app-static/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_STATIC_ROOT}),
    re_path(r'^site-media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

mck_admin_console/urls.py
from django.urls import path
from mck_admin_console import views

app_name = "mck_admin_console"

urlpatterns = [
    path('', views.LandingPage.as_view(), name='mck_landing_page'),
    path('dashboard/', views.DashboardView.as_view(), name='mck_dashboard'),
    
    path('faq_category/list/', views.FAQCategoryList.as_view(),name='mck_faq_category_list'),
    path('faq_category/create/', views.FAQCategoryCreateView.as_view(),name='mck_faq_category_create'),
    path('faq_category/<id>/edit/', views.FAQCategoryUpdateView.as_view(),name='mck_faq_category_update'),
    path('faq_category/<id>/delete/', views.FAQCategoryDeleteView.as_view(),name='mck_faq_category_delete'),
    
    path('faq/list/', views.FAQList.as_view(),name='mck_faq_list'),
    path('faq/create/', views.FAQCreateView.as_view(),name='mck_faq_create'),
    path('faq/<id>/edit/', views.FAQUpdateView.as_view(),name='mck_faq_update'),
    path('faq/<id>/delete/', views.FAQDeleteView.as_view(),name='mck_faq_delete'),
    
    path('area/list/', views.AreaListView.as_view(), name='mck_area_list'),
    path('area/create/', views.AreaCreateView.as_view(), name='mck_area_create'),
    path('area/<id>/edit/', views.AreaUpdateView.as_view(), name='mck_area_update'),
    path('area/<id>/delete/', views.AreaDeleteView.as_view(), name='mck_area_delete'),
    
    path('testimonial/list/', views.TestimonialListView.as_view(), name='mck_testimonial_list'),
    path('testimonial/create/', views.TestimonialCreateView.as_view(), name='mck_testimonial_create'),
    path('testimonial/<id>/edit/', views.TestimonialUpdateView.as_view(), name='mck_testimonial_update'),
    path('testimonial/<id>/delete/', views.TestimonialDeleteView.as_view(), name='mck_testimonial_delete'),

]

mck_auth/urls.py
from django.urls import path
from mck_auth import views

app_name = "mck_auth"

urlpatterns = [
    path('', views.LandingPage.as_view(), name='mck_landing_page'),
    path('login/', views.SignIn.as_view(), name='mck_signin'),
    path('logout/',views.LogOut.as_view(),name='mck_logout'),
    
    path('website/login/', views.WebsiteSignIn.as_view(), name='website_signin'),
    path('website/register/', views.WebsiteSignUp.as_view(), name='website_signup'),
    path('website/logout/', views.WebsiteLogOut.as_view(), name='website_logout'),
    # ... existing patterns
    path('website/password-reset/', views.WebsitePasswordReset.as_view(), name='website_password_reset'),

    path('mck-auth/role/list/', views.AccountTypeRoleList.as_view(),name='mck_role_list'),
    path('mck-auth/role/create/', views.AccountTypeRoleCreateView.as_view(),name='mck_role_create'),
    path('mck-auth/role/<id>/edit/', views.AccountTypeRoleUpdateView.as_view(),name='mck_role_update'),
    path('mck-auth/role/<id>/delete/', views.AccountTypeRoleDeleteView.as_view(),name='mck_role_delete'),
    path('mck-auth/role/<id>/update-permission/', views.AccountTypeRoleUpdatePermissionView.as_view(),name='mck_role_update_permission'),

]

mck_master/urls.py
from django.urls import path
from mck_master import views

app_name = "mck_master"

urlpatterns = [

    # Support Page Content
    path('support_page_content/list/', views.SupportPageContentList.as_view(),name='mck_support_page_content_list'),
    path('support_page_content/create/', views.SupportPageContentCreateView.as_view(),name='mck_support_page_content_create'),
    path('support_page_content/<id>/edit/', views.SupportPageContentUpdateView.as_view(),name='mck_support_page_content_update'),
    path('support_page_content/<id>/delete/', views.SupportPageContentDeleteView.as_view(),name='mck_support_page_content_delete'),

    # Category
    path('category/list/', views.CategoryList.as_view(),name='mck_category_list'),
    path('category/create/', views.CategoryCreateView.as_view(),name='mck_category_create'),
    path('category/<id>/edit/', views.CategoryUpdateView.as_view(),name='mck_category_update'),
    path('category/<id>/delete/', views.CategoryDeleteView.as_view(),name='mck_category_delete'),

    # Sub Category
    path('sub_category/list/', views.SubCategoryList.as_view(),name='mck_sub_category_list'),
    path('sub_category/create/', views.SubCategoryCreateView.as_view(),name='mck_sub_category_create'),
    path('sub_category/<id>/edit/', views.SubCategoryUpdateView.as_view(),name='mck_sub_category_update'),
    path('sub_category/<id>/delete/', views.SubCategoryDeleteView.as_view(),name='mck_sub_category_delete'),
    path('ajax/category-based/sub_category/', views.CategoryBasedSubCategoryAjax.as_view(),name='mck_category_based_sub_categories'),

    path('states/', views.StateList.as_view(), name='mck_state_list'),
    path('states/create/', views.StateCreateView.as_view(), name='mck_state_create'),
    path('states/update/<id>/edit/', views.StateUpdateView.as_view(), name='mck_state_update'),
    path('states/delete/<id>/delete/', views.StateDeleteView.as_view(), name='mck_state_delete'),
    
    
    path('citys/', views.CityList.as_view(), name='mck_city_list'),
    path('citys/create/', views.CityCreateView.as_view(), name='mck_city_create'),
    path('citys/update/<id>/edit/', views.CityUpdateView.as_view(), name='mck_city_update'),
    path('citys/delete/<id>/delete/', views.CityDeleteView.as_view(), name='mck_city_delete'),

    # Banner
    path('banner/list/', views.BannerList.as_view(),name='mck_banner_list'),
    path('banner/create/', views.BannerCreateView.as_view(),name='mck_banner_create'),
    path('banner/<id>/edit/', views.BannerUpdateView.as_view(),name='mck_banner_update'),
    path('banner/<id>/delete/', views.BannerDeleteView.as_view(),name='mck_banner_delete'),

    # Gallery
    path('gallery/list/', views.GalleryList.as_view(),name='mck_gallery_list'),
    path('gallery/create/', views.GalleryCreateView.as_view(),name='mck_gallery_create'),
    path('gallery/<id>/edit/', views.GalleryUpdateView.as_view(),name='mck_gallery_update'),
    path('gallery/<id>/delete/', views.GalleryDeleteView.as_view(),name='mck_gallery_delete'),
    
    
    path('offer/list/', views.OfferList.as_view(), name='mck_offer_list'),
    path('offer/create/', views.OfferCreateView.as_view(), name='mck_offer_create'),
    path('offer/<id>/edit/', views.OfferUpdateView.as_view(), name='mck_offer_update'),
    path('offer/<id>/delete/', views.OfferDeleteView.as_view(), name='mck_offer_delete'),


    path('client_feedback/list/', views.ClientFeedbackList.as_view(), name='mck_client_feedback_list'),
    path('client_feedback/create/', views.ClientFeedbackCreateView.as_view(), name='mck_client_feedback_create'),
    path('client_feedback/<id>/edit/', views.ClientFeedbackUpdateView.as_view(), name='mck_client_feedback_update'),
    path('client_feedback/<id>/delete/', views.ClientFeedbackDeleteView.as_view(), name='mck_client_feedback_delete'),

    path('profile/list/', views.ProfileList.as_view(), name='mck_profile_list'),
    path('profile/create/', views.ProfileCreateView.as_view(), name='mck_profile_create'),
    path('profile/<id>/edit/', views.ProfileUpdateView.as_view(), name='mck_profile_update'),
    path('profile/<id>/delete/', views.ProfileDeleteView.as_view(), name='mck_profile_delete'),
    
]    

mck_admin_console/forms.py
import sys
from django import forms
from django.forms.widgets import HiddenInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder
from crispy_forms.helper import *
from crispy_forms.layout import *
from crispy_forms.bootstrap import *
from mck_admin_console import models
from config import app_gv as gv

from mck_auth.models import AccountTypeRole


class FAQCategoryCreateUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        mode = kwargs.pop('mode', None)
        super(FAQCategoryCreateUpdateForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = str(self.fields[field_name].label).upper()
            self.fields[field_name].widget.attrs['class'] = "form-control form-control-solid"
        
        if mode == "edit":
            instance = kwargs.get('instance', None)
        save_button_name = "SAVE"

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                '',
                Row(Column(Field('name')), css_class='col-12'),
               
            ),
            ButtonHolder(
                 Div(HTML('<a class="btn btn-lg btn-secondary me-3" href="javascript:void();" onclick="history.back()">CANCEL</a>'),Submit('create_button', save_button_name, css_class='btn btn-lg btn-primary'),
                            css_class="d-flex text-right justify-content-end pt-10 col-12"), css_class="row col-12 pe-5",
            )
        )
        
    class Meta:
        model = models.FAQCategory
        exclude = ['created_on', 'updated_on', 'created_by', 'updated_by', 'datamode']


class FAQCreateUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        mode = kwargs.pop('mode', None)
        super(FAQCreateUpdateForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = str(self.fields[field_name].label).upper()
            self.fields[field_name].widget.attrs['class'] = "form-control form-control-solid"
        
        if mode == "edit":
            instance = kwargs.get('instance', None)
        save_button_name = "SAVE"

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                '',
                Row(Column(Field('faqcategory')), css_class='col-12'),
                Row(Column(Field('question')), css_class='col-12'),
                Row(Column(Field('answer')), css_class='col-12'),
               
            ),
            ButtonHolder(
                Div(
                    HTML('<a class="btn btn-lg btn-secondary me-3" href="javascript:void();" onclick="history.back()">CANCEL</a>'),
                    Submit('create_button', save_button_name, css_class='btn btn-lg btn-primary'),
                    css_class="d-flex text-right justify-content-end pt-10 col-12"
                ),
                css_class="row col-12 pe-5",
            )
        )
        
    class Meta:
        model = models.FAQ
        exclude = ['created_on', 'updated_on', 'created_by', 'updated_by', 'datamode']


class AreaCreateUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        mode = kwargs.pop('mode', None)
        super(AreaCreateUpdateForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = str(self.fields[field_name].label).upper()
            self.fields[field_name].widget.attrs['class'] = "form-control form-control-solid"
        
        if mode == "edit":
            instance = kwargs.get('instance', None)
        save_button_name = "SAVE"

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                '',
                Row(Column(Field('county')), Column(Field('name')), css_class='col-12'),
                Row(Column(Field('short_description')), css_class='col-12'),
                Row(Column(Field('address')), css_class='col-12'),
                Row(Column(Field('tag')), css_class='col-12'),
                Row(Column(Field('link')), css_class='col-12'),
               
            ),
            ButtonHolder(
                Div(HTML('<a class="btn btn-lg btn-secondary me-3" href="javascript:void();" onclick="history.back()">CANCEL</a>'),Submit('create_button', save_button_name, css_class='btn btn-lg btn-primary'),
                            css_class="d-flex text-right justify-content-end pt-10 col-12"), css_class="row col-12 pe-5",
            )
        )
        
    class Meta:
        model = models.Area
        exclude = ['created_on', 'updated_on', 'created_by', 'updated_by', 'datamode']


class TestimonialCreateUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        mode = kwargs.pop('mode', None)
        super(TestimonialCreateUpdateForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = str(self.fields[field_name].label).upper()
            self.fields[field_name].widget.attrs['class'] = "form-control form-control-solid"
        
        if mode == "edit":
            instance = kwargs.get('instance', None)
        save_button_name = "SAVE"

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                '',
                Row(Column(Field('name')), css_class='col-12'),
                Row(Column(Field('short_description')), css_class='col-12'),
                Row(Column(Field('description')), css_class='col-12'),
                Row(Column(Field('photo')), Column(Field('tags')), Column(Field('star')), css_class='col-12'),
               
            ),
            ButtonHolder(
                Div(HTML('<a class="btn btn-lg btn-secondary me-3" href="javascript:void();" onclick="history.back()">CANCEL</a>'),Submit('create_button', save_button_name, css_class='btn btn-lg btn-primary'),
                            css_class="d-flex text-right justify-content-end pt-10 col-12"), css_class="row col-12 pe-5",
            )
        )
        
    class Meta:
        model = models.Testimonial
        exclude = ['created_on', 'updated_on', 'created_by', 'updated_by', 'datamode']

mck_admin_console/templates/includes/app-header.html
<div class="app-header header sticky">
	<div class="container-fluid main-container">
		<div class="d-flex">
			<a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-bs-toggle="sidebar"
				href="javascript:void(0)"></a>
			<a class="logo-horizontal" href="index">
				<img src="{{page_kwargs.media_url}}admin_assets/images/brand/logo.png" class="header-brand-img main-logo"
					alt="mck">
				<img src="{{page_kwargs.media_url}}admin_assets/images/brand/logo-light.png" class="header-brand-img darklogo"
					alt="mck">
			</a>
			<div class="d-flex order-lg-2 ms-auto header-right-icons">
				<div class="navbar navbar-collapse responsive-navbar p-0">
					<div class="collapse navbar-collapse" id="navbarSupportedContent-4">
						<div class="d-flex">
							<a class="nav-link icon theme-layout nav-link-bg layout-setting">
								<span class="dark-layout mt-1"><i class="ri-moon-clear-line"></i></span>
								<span class="light-layout mt-1"><i class="ri-sun-line"></i></span>
							</a>
						</div>
						<!-- Theme-Layout -->
						<div class="dropdown d-flex">
							<a class="nav-link icon full-screen-link" id="fullscreen-button">
								<i class="ri-fullscreen-exit-line fullscreen-button"></i>
							</a>
						</div>
						<!-- FULL-SCREEN -->
						<div class="dropdown d-flex profile-1">
							<a href="javascript:void(0)" data-bs-toggle="dropdown"
								class="nav-link leading-none d-flex">
								<img src="{{page_kwargs.media_url}}admin_assets/images/users/user.png" style="background-color: white;" alt="profile-user"
									class="avatar  profile-user brround cover-image">
							</a>
							<div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow" data-bs-popper="none">
								<div class="drop-heading">
									<div class="text-center">
										<h5 class="text-dark mb-0 fw-semibold">{{request.user.username}}</h5>
										<span class="text-muted fs-12">{% if request.user.is_superuser %}Administrator{% else %}Staff{% endif %}</span>
									</div>
								</div>
								<a class="dropdown-item text-dark fw-semibold" href="{% url 'mck_auth:mck_logout' %}">
									<i class="dropdown-icon fe fe-log-out"></i> Sign
									out
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

mck_admin_console/templates/includes/app-sidebar.html
{% load static %}
<div class="sticky">
	<div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
	<div class="app-sidebar">
		<div class="side-header">
			<h3>MM</h3>
			<!-- <a class="header-brand1" href="">
				<img src="{{ page_kwargs.media_url }}admin_assets/images/brand/logo.png" class="header-brand-img main-logo" alt="RealEstate">
				<img src="{{ page_kwargs.media_url }}admin_assets/images/brand/logo.png" class="header-brand-img darklogo" alt="RealEstate">
				<img src="{{ page_kwargs.media_url }}admin_assets/images/brand/icon.png" class="header-brand-img icon-logo" alt="RealEstate">
				<img src="{{ page_kwargs.media_url }}admin_assets/images/brand/icon.png" class="header-brand-img icon-logo2" alt="RealEstate">
			</a> -->
		</div>

		<div class="main-sidemenu">
			
			<ul class="side-menu">
				<li class="sub-category"><h3> Management</h3></li>

				<li class="slide">
					<a class="side-menu__item has-link {% if page == 'hot_selling' %} active {% endif %}" href="{% url 'mck_admin_console:mck_dashboard' %}">
						<i class="side-menu__icon bi bi-fire"></i><span class="side-menu__label"> Dashboard</span>
					</a>
				</li>


				<li class="slide">
					<a class="side-menu__item has-link {% if page == 'hot_selling' %} active {% endif %}" href="{% url 'mck_master:mck_profile_list' %}">
						<i class="side-menu__icon bi bi-fire"></i><span class="side-menu__label"> Profile</span>
					</a>
				</li>
				
				
			</ul>

			
		</div>
	</div>
</div>

mck_admin_console/templates/includes/custom-scripts.html
<!-- JQUERY MIN JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/jquery/jquery.min.js"></script>

<!-- BOOTSTRAP5 BUNDLE JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/bootstrap/popper.min.js"></script>
<script src="{{page_kwargs.media_url}}admin_assets/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- MOMENT JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/moment/moment.min.js"></script>

mck_admin_console/templates/includes/custom-styles.html
<!-- BOOTSTRAP CSS -->
<link id="style" href="{{page_kwargs.media_url}}admin_assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- STYLE CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/style.css" rel="stylesheet">

<!--- PLUGINS CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/plugins.css" rel="stylesheet">

<!--- ICONS CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/icons.css" rel="stylesheet">

<!--- ANIMATE CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/animated.css" rel="stylesheet">

mck_admin_console/templates/includes/footer.html
{% load static %}
            <footer class="footer">
                <div class="container">
                    <div class="row align-items-center flex-row-reverse">
                        <div class="col-lg-12 col-sm-12   text-center">
                            Copyright © 2025 <a href="/">Mckbytes</a>. All rights
                            reserved.
                        </div>
                    </div>
                </div>
		    </footer>

mck_admin_console/templates/includes/scripts.html
<!-- BACK TO TOP -->
<a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>

<!-- JQUERY MIN JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/jquery/jquery.min.js"></script>

<!-- BOOTSTRAP5 BUNDLE JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/bootstrap/popper.min.js"></script>
<script src="{{page_kwargs.media_url}}admin_assets/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- PERFECT-SCROLLBAR JS  -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/p-scroll/perfect-scrollbar.js"></script>
<script src="{{page_kwargs.media_url}}admin_assets/plugins/p-scroll/pscroll.js"></script>

<!-- CIRCLE PROGRESS JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/circle-progress/circle-progress.min.js"></script>

<!-- MOMENT JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/moment/moment.min.js"></script>

<!-- NEWS TICKER JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/newsticker/breaking-news-ticker.min.js"></script>
<script src="{{page_kwargs.media_url}}admin_assets/plugins/newsticker/newsticker.js"></script>

<!-- SIDEMENU JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/sidemenu/sidemenu.js"></script>

<!-- RIGHT SIDEBAR JS -->
<script src="{{page_kwargs.media_url}}admin_assets/plugins/sidebar/sidebar.js"></script>

mck_admin_console/templates/includes/styles.html
<!-- BOOTSTRAP CSS -->
<link id="style" href="{{page_kwargs.media_url}}admin_assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- STYLE CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/style.css" rel="stylesheet">

<!--- PLUGINS CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/plugins.css" rel="stylesheet">

<!--- ICONS CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/icons.css" rel="stylesheet">

<!--- ANIMATE CSS -->
<link href="{{page_kwargs.media_url}}admin_assets/css/animated.css" rel="stylesheet">