config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path, include
from django.views.static import serve
from django.contrib.auth import views as auth_views
from config import app_seo as seo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('mck_auth.urls', namespace='mck_auth')),
    path('mck-master/', include('mck_master.urls', namespace='mck_master')),

    path('change-password/',auth_views.PasswordChangeView.as_view(
                                        extra_context={'page_kwargs':seo.get_page_tags("password_change")}),
                                        name='password_change'),
    path('change-password/complete/',auth_views.PasswordChangeDoneView.as_view(
                                        extra_context={'page_kwargs':seo.get_page_tags("password_change_done")}),
                                        name='password_change_done'),

    path('', include('mck_website.urls', namespace='vlr_website')),
    path('mck-admin-console/', include('mck_admin_console.urls', namespace='mck_admin_console')),
    path('squarebox/', include('squarebox.urls', namespace='squarebox')),

    re_path(r'^app-static/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_STATIC_ROOT}),
    re_path(r'^site-media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

mck_auth/urls.py
from django.urls import path
from mck_auth import views

app_name = "mck_auth"

urlpatterns = [
    path('', views.LandingPage.as_view(), name='mck_landing_page'),
    path('login/', views.SignIn.as_view(), name='mck_signin'),
    path('logout/',views.LogOut.as_view(),name='mck_logout'),
    
    path('website/login/', views.WebsiteSignIn.as_view(), name='website_signin'),
    path('website/register/', views.WebsiteSignUp.as_view(), name='website_signup'),
    path('website/logout/', views.WebsiteLogOut.as_view(), name='website_logout'),
    # ... existing patterns
    path('website/password-reset/', views.WebsitePasswordReset.as_view(), name='website_password_reset'),

    path('mck-auth/role/list/', views.AccountTypeRoleList.as_view(),name='mck_role_list'),
    path('mck-auth/role/create/', views.AccountTypeRoleCreateView.as_view(),name='mck_role_create'),
    path('mck-auth/role/<id>/edit/', views.AccountTypeRoleUpdateView.as_view(),name='mck_role_update'),
    path('mck-auth/role/<id>/delete/', views.AccountTypeRoleDeleteView.as_view(),name='mck_role_delete'),
    path('mck-auth/role/<id>/update-permission/', views.AccountTypeRoleUpdatePermissionView.as_view(),name='mck_role_update_permission'),

]

mck_website/urls.py
from django.urls import path
from mck_website import views

app_name = "mck_website"

urlpatterns = [

    # path(".well-known/pki-validation/0021C33903EBC802E268A3D626130F22.txt", views.pki_validation_view, name="pki_validation"),
    path('', views.HomePage.as_view(), name='home_page'),
    path('about/', views.AboutPage.as_view(), name='about_page'),
    path('pricing/', views.PropertyLegalServicesPage.as_view(), name='pricing'),
    path('our-services/', views.OurServicesPage.as_view(), name='our_services_page'),
    path('privacy-policy/', views.PrivacyPolicyPage.as_view(), name='privacy_policy_page'),
    path('terms/', views.TermsPage.as_view(), name='terms_page'),
    path('solar/',views.SolarPage.as_view(), name='solar_page'),
    path('fencing/',views.FencingPage.as_view(), name='fencing_page'),
    path('land-levelling/',views.LandLevellingPage.as_view(), name='land_levelling_page'),
    path("Profile-detail/", views.ProfilePage.as_view(), name="mck_property_page"),
    path('property-details/<int:pk>/', views.PropertyDetailPage.as_view(), name='property_detail'),
    path(
        "property_create/",
        views.PropertyCreatePage.as_view(),
        name="mck_property_create_page",
    ),
    path(
        "maintenances/",
        views.MaintenancesCreatePage.as_view(),
        name="property_maintenance_page",
    ),
    path(
        "enquiry/",
        views.EnquiryCreatePage.as_view(),
        name="property_enquiry_page",
    ),
    path('ajax/property/save/', views.PropertySaveView.as_view(),name='mck_ajax_property_save'),
    path('ajax/maintenances/save/', views.MaintenanceSaveView.as_view(),name='mck_ajax_maintenance_save'),
    path('ajax/lead/save/', views.EnquirySaveView.as_view(),name='mck_ajax_enquiry_save'),


    # path(
    #     "profile/",
    #     views.EnquiryCreatePage.as_view(),
    #     name="profile_page",
    # ),

   path('ajax/profile/save/', views.ProfileSaveView.as_view(),name='mck_ajax_profile_save'),
#    path("profile/<int:pk>/", views.ProfileDetailPage.as_view(), name="profile_detail"),
# Correct order
            path("profile/<int:pk>/", views.ProfileDetailPage.as_view(), name="profile_detail"),
            path("profile/", views.EnquiryCreatePage.as_view(), name="profile_page"),
            path("my-profile/", views.MyProfilePage.as_view(), name="my_profile"),
            # mck_website/urls.py
            path(
                "ajax/my-profile/save/",
                views.ajax_profile_save,
                name="mck_ajax_my_profile_save"
            ),



]

mck_master/models.py
from django.db import models
from config import app_gv as gv
from django_countries.fields import CountryField
from django.conf import settings
from django_countries.fields import CountryField



# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    iso_4217_alpha = models.CharField(max_length=200)
    iso_4217_numeric = models.CharField(max_length=200)
    iso2 = models.CharField(max_length=2)
    iso3 = models.CharField(max_length=3)
    capital_city = models.CharField(max_length=200)
    telephone_calling_code = models.CharField(max_length=5)
    internet_domain_code = models.CharField(max_length=5)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'country'

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    code = models.CharField(max_length=32, unique=True, db_index=True)
    country = models.ForeignKey(Country, related_name='country',on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'state'

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    code = models.CharField(max_length=32, unique=True, db_index=True)
    state = models.ForeignKey(State, related_name='state',on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'city'

class SupportPageContent(models.Model):
    support_key = models.CharField(max_length=255)
    support_value = models.CharField(max_length=255)
    support_description = models.TextField(blank=True, null=True)
    image = models.CharField(max_length=255, blank=True, null=True)
    content_type = models.CharField(max_length=64, blank=True, null=True, db_index=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    datamode = models.CharField(max_length=1, default='A', choices=gv.DATAMODE_CHOICES)

    def __str__(self):
        return "{0}".format(self.support_value)

    class Meta:
        db_table = 'support_page_content'


class VersionControl(models.Model):
    app = models.CharField(choices=gv.APP_LIST, default='CUS_ANDROID_APP', max_length=100)
    version = models.CharField(max_length=10)
    released_on = models.DateTimeField(auto_now_add=True)
    datamode = models.CharField(max_length=5, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'version_control'

    def __str__(self):
        return "{0}-{1}".format(self.app, self.version)


class MasterPermission(models.Model):
    app_name = models.CharField(max_length=255, db_index=True) # App Name
    class_name = models.CharField(max_length=255, unique=True, db_index=True) # Class Name
    module_name = models.CharField(max_length=255)
    function_name = models.CharField(max_length=255) # Read, Update, delete, btn action
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    def __str__(self):
        return f"{self.class_name} - {self.function_name}"

    class Meta:
        db_table = 'master_permission'



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="ddata", blank=True, null=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="ddata", blank=True, null=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'sub_category'

    def __str__(self):
        return self.name


class Banner(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="ddata", blank=True, null=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'banner'

    def __str__(self):
        return self.name


class Gallery(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="ddata", blank=True, null=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'gallery'

    def __str__(self):
        return self.name


class Offers(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="ddata", blank=True, null=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    class Meta:
        db_table = 'offers'
    
    def __str__(self):
        return self.name


class ClientFeedback(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    feedback = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to="ddata", blank=True, null=True)
    place = models.CharField(max_length=100, blank=True, null=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)

    
    def __str__(self):
        return ''
    
    class Meta:
        db_table = 'client_feedback'
        


class Profile(models.Model):
    MARITAL_STATUS_CHOICES = [
        ('S', 'Single'),
        ('M', 'Married'),
        ('D', 'Divorced'),
        ('W', 'Widowed'),
    ]

    user = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE,
    related_name='profiles'
)


    # user = models.CharField(max_length=50, blank=True)
    gender = models.CharField(max_length=10, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])
    dob = models.DateField(null=True, blank=True)
    religion = models.CharField(max_length=50, blank=True)
    caste = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    bio = models.TextField(blank=True)
    profile_photo = models.ImageField(upload_to='profile_photos/', blank=True, null=True)
    location = models.TextField(blank=True)
    education = models.CharField(max_length=100, blank=True)
    occupation = models.CharField(max_length=100, blank=True)
    annual_income = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    marital_status = models.CharField(max_length=1, choices=MARITAL_STATUS_CHOICES, blank=True)
    created_by = models.CharField(max_length=8)
    updated_by = models.CharField(max_length=8)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    # datamode = models.CharField(max_length=20, default='A', choices=gv.DATAMODE_CHOICES)
    datamode = models.CharField(
    max_length=1,
    choices=gv.DATAMODE_CHOICES,  # e.g., [('A','Active'),('I','Inactive'),('D','Deleted')]
    default='A',
    blank=False,
    null=False
)


    
    def __str__(self):
        if self.user:
            return str(self.user)
        return f"Profile-{self.id}"

    
    class Meta:
        db_table = 'profile'

mck_website/templates/includes/hero_2.html
<style>
    .fixed-bg {
        background-image: url('https://i.pinimg.com/1200x/99/c9/54/99c954fe61d60100c58611588f101e9a.jpg');
        background-attachment: fixed;
        background-size: cover;
        background-position: center;
        min-height: 70vh;
        width: 100%;
        position: relative;
    }

    .overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
        padding: 20px;
    }

    h1 {
        font-size: 3.5rem;
        color: #fff;
        margin-bottom: 10px;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
    }

    h2 {
        font-size: 2rem;
        color: #fff;
        margin-bottom: 15px;
        font-weight: 500;
    }

    .tagline {
        font-size: 1.4rem;
        color: #fff;
        margin-bottom: 40px;
        max-width: 800px;
    }

    .buttons {
        display: flex;
        gap: 20px;
        flex-wrap: wrap;
        justify-content: center;
    }

    .btn {
        padding: 15px 30px;
        border-radius: 50px;
        font-size: 1.1rem;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        transition: all 0.3s ease;
        text-decoration: none;
    }

    .btn-primary {
        background: #ffbf00;
        color: #080808;
        border: 2px solid #ffbf00;
    }

    .btn-primary:hover {
        background: #050505;
        color: white;
    }

    .btn-secondary {
        background: #ffbf00;
        color: #080808;
        border: 2px solid white;
    }

    .btn-secondary:hover {
        background: white;
        color: #0a0a0a;
    }

    /* 🔹 RESPONSIVE DESIGN */
    @media (max-width: 992px) {
        h1 {
            font-size: 2.8rem;
        }
        h2 {
            font-size: 1.6rem;
        }
        .tagline {
            font-size: 1.2rem;
        }
    }

    @media (max-width: 768px) {
        .fixed-bg {
            background-attachment: scroll; /* prevents jitter on iOS */
        }
        h1 {
            font-size: 2.2rem;
        }
        h2 {
            font-size: 1.4rem;
        }
        .tagline {
            font-size: 1rem;
            max-width: 95%;
        }
        .buttons {
            flex-direction: column;
            gap: 15px;
        }
        .btn {
            width: 220px;
            font-size: 1rem;
        }
    }

    @media (max-width: 480px) {
        h1 {
            font-size: 1.8rem;
        }
        h2 {
            font-size: 1.2rem;
        }
        .tagline {
            font-size: 0.95rem;
        }
        .btn {
            width: 200px;
            padding: 12px 25px;
            font-size: 0.9rem;
        }
    }
</style>

<div class="fixed-bg">
    <div class="overlay">
        <h1>Square Box</h1>
        <h2>Find Your Dream Property</h2>
        <p class="tagline">Looking to Buy a new property or Sell an existing one? RealHomes provides an easy solution!</p>
        <div class="buttons">
            <a href="{% url 'mck_website:mck_property_create_page' %}" class="btn-custom">Submit Property</a>
            <a href="{% url 'mck_website:mck_property_page' %}" class="btn-custom">Browse Properties</a>
        </div>
    </div>
</div>

mck_website/templates/includes/property_display.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />

<style>
    :root {
        --theme-red: #c60000;
        --card-bg: #ffffff;
    }

   

    /* Heading Style */
    .section-title {
        font-family: 'Playfair Display', serif;
        font-size: 2.5rem;
        font-weight: 700;
        margin-bottom: 10px;
    }
    
    .heart-divider {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px;
        margin-bottom: 40px;
    }
    .heart-divider::before, .heart-divider::after {
        content: "";
        height: 1px;
        width: 50px;
        background: #ddd;
    }

    /* Slider Container */
    .swiper {
        padding: 20px 10px 50px 10px !important;
    }

    /* Card Styling */
    .matrimony-card {
        background: var(--card-bg);
        border-radius: 15px;
        padding: 15px;
        box-shadow: 0 10px 30px rgba(0,0,0,0.08);
        transition: all 0.4s ease;
        border: 1px solid #f0f0f0;
        height: 100%;
        text-align: center;
    }

    .matrimony-card:hover {
        transform: translateY(-10px);
        box-shadow: 0 15px 45px rgba(198, 0, 0, 0.1);
    }

    .photo-wrapper {
        width: 100%;
        height: 250px;
        border-radius: 12px;
        overflow: hidden;
        margin-bottom: 15px;
    }

    .photo-wrapper img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .profile-name {
        color: var(--theme-red);
        font-size: 1.5rem;
        font-weight: 600;
        margin-bottom: 15px;
    }

    .profile-data-list {
        margin-bottom: 20px;
    }

    .data-row {
        display: flex;
        justify-content: space-between;
        padding: 8px 5px;
        border-bottom: 1px solid #f5f5f5;
        font-size: 0.9rem;
    }

    .data-label { color: #888; }
    .data-value { color: #333; font-weight: 500; }

    /* Footer Action */
    .view-link {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px;
        color: #666;
        text-decoration: none;
        font-weight: 600;
        font-size: 0.85rem;
        transition: color 0.3s;
    }
    .view-link i {
        font-size: 1.2rem;
        color: #999;
    }
    .view-link:hover { color: var(--theme-red); }

    /* Custom Navigation Arrows (Matching Image) */
    .swiper-button-next, .swiper-button-prev {
        background: #555;
        width: 35px !important;
        height: 35px !important;
        border-radius: 50%;
        color: white !important;
    }
    .swiper-button-next:after, .swiper-button-prev:after {
        font-size: 14px !important;
        font-weight: bold;
    }

    /* Main Red Button */
    .view-all-btn {
        background: var(--theme-red);
        color: white;
        padding: 12px 30px;
        border-radius: 50px;
        text-decoration: none;
        display: inline-flex;
        align-items: center;
        gap: 10px;
        font-weight: 600;
        transition: background 0.3s;
    }
    .view-all-btn:hover {
        background: #a00000;
        color: white;
    }
</style>

<section class="featured-section m-5">
    <div class="container text-center">
        <h2 class="section-title">Featured <span style="color:#555">Profiles</span></h2>
        <div class="heart-divider">
            <i class="fas fa-heart" style="color: var(--theme-red); font-size: 10px;"></i>
        </div>

        <div class="swiper profile-slider">
            <div class="swiper-wrapper">
                {% for p in profile %}
                <div class="swiper-slide">
                    <div class="matrimony-card">
                        <div class="photo-wrapper">
                            {% if p.profile_photo %}
                                <img src="{{ p.profile_photo.url }}" alt="{{ p.user }}">
                            {% else %}
                                <div style="background:#eee; height:100%; display:flex; align-items:center; justify-content:center;">
                                    <i class="fas fa-user-circle fa-5x text-muted"></i>
                                </div>
                            {% endif %}
                        </div>

                        <h3 class="profile-name">
  {{ p.user.first_name }} {{ p.user.last_name }}
</h3>


                        <div class="profile-data-list">
                            <div class="data-row">
                                <span class="data-label">Age</span>
                                <span class="data-value">{{ p.dob|timesince|slice:":2" }} Years</span>
                            </div>
                            <div class="data-row">
                                <span class="data-label">Location</span>
                                <span class="data-value">{{ p.location|default:"Karachi" }}</span>
                            </div>
                            <div class="data-row" style="border:none">
                                <span class="data-label">Status</span>
                                <span class="data-value">{{ p.get_marital_status_display|default:"Single" }}</span>
                            </div>
                        </div>

                        <a href="{% url 'mck_website:profile_detail' p.id %}" class="view-link">
                            <i class="far fa-image"></i> View Profile
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>

        <a href="{% url 'mck_website:mck_property_page' %} " class="view-all-btn mt-4">
            View all Profiles <i class="fas fa-arrow-circle-right"></i>
        </a>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script>
    function shuffleSlides() {
        const wrapper = document.querySelector('.profile-slider .swiper-wrapper');
        const slides = Array.from(wrapper.children);

        for (let i = slides.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [slides[i], slides[j]] = [slides[j], slides[i]];
        }

        slides.forEach(slide => wrapper.appendChild(slide));
    }

    shuffleSlides();
</script>

<script>
    const swiper = new Swiper('.profile-slider', {
        slidesPerView: 1,
        spaceBetween: 20,
        loop: true,
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
        breakpoints: {
            640: { slidesPerView: 2 },
            1024: { slidesPerView: 3 },
            1200: { slidesPerView: 4 }
        },
        autoplay: {
            delay: 3000,
            disableOnInteraction: false,
        }
    });
</script>

mck_website/templates/includes/services.html
{% load static %}
<style>
.services {
    background: #fff;
    
    text-align: center;
}

.section-title {
    font-size: 28px;
    font-weight: 700;
    margin-bottom: 50px;
    color: #222;
}

.services-line {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 60px;
}

.service-item {
    text-align: center;
    transition: transform 0.3s ease, color 0.3s ease;
    cursor: pointer;
}

.service-item:hover {
    transform: translateY(-5px);
}

.service-icon {
    font-size: 40px;
    margin-bottom: 12px;
    color: #29abff;
    transition: color 0.3s ease;
}

.service-item:hover .service-icon {
    color: #29abff;
}

.service-item h3 {
    font-size: 16px;
    font-weight: 600;
    color: #333;
    margin: 0;
}

/* Responsive */
@media (max-width: 768px) {
    .services-line {
        gap: 40px;
    }
    .section-title {
        font-size: 24px;
    }
}
.service-icon {
    width: 70px;  
    height: 70px;
    margin: 0 auto 15px;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    border-radius: 15px; /* rounded corners for modern look */
    transition: transform 0.3s ease;
}

.service-icon img {
    width: 100%;
    height: 100%;
    object-fit: cover; /* keep aspect ratio */
    transition: transform 0.3s ease;
}

.service-item:hover .service-icon img {
    transform: scale(1.1); /* zoom effect on hover */
}

</style>
<section class="services">
  <div class="container">
    <h2 class="section-title">Our Services</h2>
    <div class="services-line">

      <!-- Buy -->
      <a href="{% url 'mck_website:mck_property_page' %}" class="service-item">
        <div class="service-icon">
          <img src="https://cdn-icons-png.flaticon.com/512/619/619034.png" alt="Buy">
        </div>
        <h3>Buy</h3>
      </a>

      <!-- Rent -->
      <a href="{% url 'mck_website:mck_property_create_page' %}" class="service-item">
        <div class="service-icon">
          <img src="{% static 'images/section/sell-or-rent-property.png' %}" alt="Rent">
        </div>
        <h3>Rent</h3>
      </a>

      <!-- Maintenance -->
      <a href="{% url 'mck_website:property_maintenance_page' %}" class="service-item">
        <div class="service-icon">
          <img src="{% static 'images/section/property-management.png' %}" alt="Maintenance">

        </div>
        <h3>Maintenance</h3>
      </a>

      <!-- Legal Services -->
      <a href="{% url 'mck_website:property_legal_services_page' %}" class="service-item">
        <div class="service-icon">
          <img src="{% static 'images/section/property-legal-services.png' %}" alt="Legal Services">
        </div>
        <h3>Legal Services</h3>
      </a>

      <!-- Fencing -->
      <a href="{% url 'mck_website:fencing_page' %}" class="service-item">
        <div class="service-icon">
          <img src="{% static 'images/section/fencing.png' %}" alt="Fencing">
        </div>
        <h3>Fencing</h3>
      </a>

      <!-- Land Levelling -->
      <a href="{% url 'mck_website:land_levelling_page' %}" class="service-item">
        <div class="service-icon">
          <img src="{% static 'images/section/b.jpg' %}" alt="Land Levelling">
        </div>
        <h3>Land Levelling</h3>
      </a>    

      <!-- Solar -->
      <a href="{% url 'mck_website:solar_page' %}" class="service-item">
        <div class="service-icon">
          <img src="{% static 'images/section/solar.png' %}" alt="Solar">
        </div>
        <h3>Solar</h3>
      </a>

    </div>
  </div>
</section>